### ISSUE TITLE
Can the link to the host's docker socket be removed

### ISSUE THREAD

**Issue by mc0e** [sameersbn/docker-redmine#101]
You recommend providing the redmine container with access to the host's docker.sock file via a volume.  Is this really necessary?  What's it used for?

If this really is necessary, there should be a note in the README file explaining what it is for.

**Comment by mc0e** [comment]
In a similar vein, it might be better to advocate use of a separate container for the data volume rather than using a host directory.

**Comment by mc0e** [comment]
Am I right in thinking that the connection to docker in the host system is only used in assets/init to check for the DB host, and so long as the $DB_HOST environment variable is set, this would never be used?

**Comment by sameersbn** [comment]
@mc0e i do not endorse volume mounting the docker binary and socket in the container. This is only meant to allow new users to quickly try out redmine before they decide that want to use redmine. In production environments you should manually complete the process of setting up a database and linking it with the redmine image.

There seems to be a lot of confusion amongst users here and I am considering removing the feature from the image altogether, now that you can use fig/docker-compose instead.

Using a separate data only container is completely the users personal choice. Personally I do not advocate use of separate data only containers.

There are certain use cases when you might want to create a separate data container which I believe depend on your setup/environment. For example, say you want to save the data volume on a network share, then you could use and image to mount a network share and then import that volume `--volumes-from` into the redmine image. This is a very specific use case and there could be similar use cases. But creating a separate data only container just because you can just seems pointless to me.

I have noticed that a lot of people use data only containers. But I have failed to understand their use in normal use cases.  I would imagine you want to simplify your setup instead of unnecessarily complicating stuff.  Just mount a volume with the redmine image and be done with it.
