### ISSUE TITLE
DB_PORT may contain full tcp:// URI if db alias is 'db', prompting sed error

### ISSUE THREAD

**Issue by bradjones1** [sameersbn/docker-redmine#114]
If the database alias is passed in to the container as 'db', the DB_PORT variable is not from the user but rather from Docker, which is treating this as <alias>_PORT. In that case, it contains slashes, which screws up sed at https://github.com/sameersbn/docker-redmine/blob/master/assets/init#L245 This is pretty easily avoidable but in the same breath, "db" is a very common alias for a database and this fails rather inelegantly.

I can probably put together a pull request on this sometime soon but thought I'd open a ticket in the meantime in case this trips up anyone else.

**Comment by sameersbn** [comment]
@bradjones1 you have to use the link alias as `mysql` when linking a mysql container or use the alias `postgresql` when linking a postgresql container. A side effect of using a different alias name is that it allows me to easily figure out the database server in use and appropriately set the `DB_TYPE` parameter in the entrypoint script

Regarding use of `db` the alias. Initially I was trying to use this, but since my entrypoint uses `DB_PORT` variable it would conflict with the `<alias>_PORT` variable created by docker. This is essentially the issue you are seeing. To be able to use the alias `db` would require that the `DB_*` configuration options be changed to something like `DATABASE_*`. This will create an issue for existing installations and additionally users will have to specify the type of database in use.

**Comment by bradjones1** [comment]
I get that, though this probably could be avoided with some better documentation (I'll submit a PR today) since "should be called mysql" is very different from "can't be called db." You can name the alias whatever you like if you also specify the DB_TYPE, so there is definitely some room for error if you're used to using the same aliases on all your containers.

Thanks for the reply and for an awesome project.

**Comment by sameersbn** [comment]
@bradjones1 this is already documented in the linking container sections of the readme https://github.com/sameersbn/docker-redmine#linking-to-mysql-container. However the documentation can surely be improved.

**Comment by mklatsky** [comment]
I am seeing this issue as well. I have not found a combination of aliases which will allow a successful redmine launch. If I alias my link: 
links:
   - mysql:mydb

and set DB_TYPE: mysql

redmine will not start as it cannot find the db host.

If I set my alias to "db":
links:
   - mysql:db

then I receive the 'sed' error noted above.

**Comment by sameersbn** [comment]
Please refer to my first comment in this thread.

**Comment by sameersbn** [comment]
Please refer to my first comment in this thread.

**Comment by mklatsky** [comment]
As I understand your comment- the alias should simply be "mysql", as in:

links:
  - mysql:mysql

If the above is correct, this still fails, as redmine gets stuck "Waiting for database server to accept connections..".

The same error exists if I specify the DB_HOST and DB_PORT.

**Comment by sameersbn** [comment]
@mklatsky the `--link mysql:mysql` should work. Can you please share your docker run commands to start mysql and redmine?

**Comment by jcormier** [comment]
Closing due to old age
