### ISSUE TITLE
Plugin : rake versions are not right

### ISSUE THREAD

**Issue by maximelebastard** [sameersbn/docker-redmine#151]
Hi,

I try to install the ekanban plugin (https://github.com/samchen2009/ekanban) in my container. I pulled it in the plugins directory, and I created a pre-install.sh file that contains this (as indicated in the plugin doc):

```
bundle install
rake redmine:plugins:migrate RAILS_ENV=production
```

But I get this error when restarting the container:
```
You have already activated rake 10.1.0, but your Gemfile requires rake 10.4.2. Prepending `bundle exec` to your command may solve this.
```

How are the version managed in the container ? Can I update rake or something to get rid of this error ?

**Comment by sameersbn** [comment]
@maximelebastard You dont need to add those lines to `pre-install.sh` script. That is automatically done my the image when it is started.

If the above change does not resolve the issue, then try deleting the `/tmp` directory from the data volume and starting the container again. If that does not help, then edit the `Gemfile` of the plugin so that it uses the same rake version.

**Comment by maximelebastard** [comment]
It stills not work for this plugin, but I think it's related to Redmine 3 compatibility : errors are about var types in migrations or functions that don't exists anymore.
But I installed TinyMCE plugin and it works ! Thank you for the help !
