### ISSUE TITLE
Not able to use Redmine Bootstrap Kit

### ISSUE THREAD

**Issue by mike-battistella** [sameersbn/docker-redmine#176]
I cannot install the https://www.redmine.org/plugins/redmine_bootstrap_kit plugin. If I install it in the plugin dir and start the docker instance with redmine there is some error. The redmine_agile_light plugin works.
I have the same problem with redmine_ckeditor.

Where do I find useful log info? Maybe the rake install script had some errors?

**Comment by EzVoodoo** [comment]
I am pretty sure this was caused by the fact that installing these plugins requires new gems to be installed, which is not that straightforward given the current docker image. I had the same problem attempting to install the knowledge_base plugin.

It would be very helpful if the author can comment on this issue. Thx!

**Comment by sameersbn** [comment]
@mike-battistella Are you still facing the issue? If yes, can you please state the redmine version in use and also check of the plugin you're trying to install is compatible with the redmine version?

(sorry for the horribly late response time :grimacing: )

**Comment by frank-dspeed** [comment]
i close because no response happend feel free to reopen
