### ISSUE TITLE
putting theme and plugin to /home/redmine/data make no effect

### ISSUE THREAD

**Issue by lubobill1990** [sameersbn/docker-redmine#180]
The backup and files directory paths are set in configuration.yml, so files are uploaded to /home/redmine/data/files, but theme and plugin directories are not.

As a result, adding new themes to /home/redmine/data/theme has no use.

So, the THEME and PLUGIN part in README.md is wrong.

**Comment by sheim-dev** [comment]
I just installed a theme and a plugin in exactly the way advertised in README.md.

How do you start the docker-redmine container? Maybe you lack the volume bind mount for `/home/redmine/data`?

**Comment by sameersbn** [comment]
@lubobill1990 were you able to resolve the issue?  can we close it? or are you still looking for a resolution?

**Comment by josiah47** [comment]
It seems that /home/redmine/redmine/plugins is not a symlink to /home/redmine/data/plugins inside the docker container
or do I have something wrong?

**Comment by eriko** [comment]
There is a comment in the howto able using the 2.x branch if you want plugins.  This leads me to believe that the container for 3.3x is not set up to support plugins.  As to why that is I have no idea.
I am going to try resetting it up so that 3.3 can have plugins.  Maybe they I will discover why it is setup this way now.

**Comment by lubobill1990** [comment]
Late reply. Since I don't use docker to deploy redmine now, I will close this issue.
