### ISSUE TITLE
Add: reload command for local plugin development

### ISSUE THREAD

**Issue by knulle** [sameersbn/docker-redmine#238]
what will be the best way to develop plugins with the docker-redmine image / container ?

Just modifying the /srv/docker/redmine/redmine/plugins/myplusig/* and restarting the docker-container again and again is a bit tedious.

So I thought about modifying /home/redmine/redmine/plugins/myplugin/* ... but then I've to restart the docker container to activate the modifications ... of course all are gone.
Any suggestions ?
Thx in advance

**Comment by jcormier** [comment]
Something like
```
$ docker-compose exec redmine supervisorctl restart unicorn
unicorn: stopped
unicorn: started
```

**Comment by jcormier** [comment]
Hmm looks like the start script copies the plugins in the docker.  This is done by install_plugins() in assets/runtime/functions.

Well here is a hack.  Create the following file and then you can execute it via `docker-compose exec redmine bash /home/redmine/data/install_plugins.sh`. Or something similar if not using docker-compose

redmine-data/install_plugin.sh
```
#!/bin/bash
## Script to run install_plugins
set -e
source ${REDMINE_RUNTIME_DIR}/functions

install_plugins
```

**Comment by frank-dspeed** [comment]
@jcormier please think about a better solution for our install script so that plugin developers can use that more easy its essential that plugins work with redmine this is a primary goal for this project.

**Comment by jcormier** [comment]
Okay so heres what I think the problem is.  This docker image does not directly mount the plugins directory where the server can get to it. Instead on start-up the install_plugins function is called which checks to see if the plugins have changed and then copies them and runs the migrate tasks.

This becomes a problem because you can't simply refresh your browser when you make a plugin change. 

I think the easiest solution would be to provide a app:install_plugins which calls install_plugins.  And while we are at it, add a app:install_themes.
https://github.com/sameersbn/docker-redmine/blob/18231b656e24c8995ce3d9ebef1992d3cb1ebedf/entrypoint.sh#L28

Though perhaps those don't work when using `docker exec` instead of `docker run`.

**Comment by frank-dspeed** [comment]
@jcormier what do you think about a simple --env parameter like GITLAB_DEVELOP=plugin/name or template/name that tracks file changes and does auto reload that?

**Comment by jcormier** [comment]
I think adding an auto-reloader might be too much bloat for the redmine image.  If we provide a callable function for the user which reloads the plugins/themes then they could always setup an auto-reloader if they were so inclined.

**Comment by frank-dspeed** [comment]
@jcormier a autoreloader is already existing via file watchers its in the linux kernel

**Comment by frank-dspeed** [comment]
@jcormier ok i aggree i will implament a reload command that  will get documented with information about 
https://wiki.ubuntuusers.de/inotify/

**Comment by 42robots** [comment]
What about just integrating such a command as "supervisorctl restart unicorn" into  gulp setup? Would be nice if changing things a custom plugin or theme.

**Comment by jcormier** [comment]
@42robots Restarting unicorn is not really what needs to be done.  Not sure what gulp is, a quick google search seems to indicate it relies on node.js which I doubt we'd want to add as a dependency.

**Comment by jcormier** [comment]
@42robots  Added redmine-install-plugins command. See commit  8cde848

**Comment by 42robots** [comment]
@jcormier Thanks for the feedback! Best
