### ISSUE TITLE
ADD: The possibility of obtaining emails via pop3

### ISSUE THREAD

**Issue by iridiumhawk** [sameersbn/docker-redmine#269]
I have a problem with receiving email via IMAP from my local server. A self-signed certificate is not accepted. Is it possible to configure the receiving mail via pop3?

**Comment by ejmvar** [comment]
I was in trouble obtaining IMAP emails from gmail, due to security controls at Gmail side.

As I have many projects, suscribing to specialized email accounts, my setup uses the following script for each email I want to suscribe:
Adding this to my crontab ensures Redmine projects receive email updates.

Script: "CRON_Redmine_Email.sh"

`
# several constants, instance specific

# ## where is my DOCKER-COMPOSE sameersbn_redmine started from?
O=/home/CI/sameersbn_redmine.v3-63132-63133
# ## where backups must live?
B=/home/CI/sameersbn_redmine.v3-63132-63133/FILES/backups
# ## my docker instance name (from docker ps)
I=sameersbnredminev36313263133_redmine_1
# ## timestamped name for backup
F="`date_fmt_ejmv.sh`_redmine.sql.gz"

DOCKER_RUN=" docker exec -it ${I}     "
RAKE_RUN_PRE="  bundle exec  "

echo "### project=zzz ###"
OPTS="  username=EmailUserName     password=EmailPassword      project=ProjectName      "
${DOCKER_RUN}  ${RAKE_RUN_PRE}  ${RAKE_RUN}  ${MAIL_COMMON}  ${OPTS}
`

Same way, I added backup:

`
cd $O
echo "### MYSQL DUMP : Redmine ###"
docker exec -it ${I}  mysqldump -h mysql -u MY_USER -pMY_PASS  --add-drop-table  redminep   --result-file=../data/backups/redmine.sql 

cd $B
cat redmine.sql | gzip > "$F"

`

Replace with your own data.

Hope this helps.

**Comment by jcormier** [comment]
Closed due to old age
