### ISSUE TITLE
How to configure to send mail for mailing list?

### ISSUE THREAD

**Issue by khoi-thinh** [sameersbn/docker-redmine#274]
Hello,
I used to install redmine and configure sendmail (not use docker) in Centos 6 to send notification about new issue/new project to everyone in mailing list. Basically, i just install sendmail and then add these line into configuration.yml
production:
  email_delivery:
    delivery_method: :sendmail
Then changed Email notification in Redmine and everything is done!

But for installing with Docker (not Docker-compose), i don't understand how to configure to send mail to my mailing list (not gmail), for example project-redmine@company.com
Any help would be greatly appreciated!

**Comment by jcormier** [comment]
I'm not sure, If you want to install sendmail and configure redmine to use it. Then you'd want to create a new Dockerfile which inherits this one. Install and setup sendmail and then overwrite the configuration.yml file.
Heres the commit where he first added it.
https://github.com/sameersbn/docker-redmine/commit/b7e385dbfa0a7587a1d0162374aa49508ea8c211

**Comment by frank-dspeed** [comment]
@jcormier what do you think about installing sendmail fast on startup if no gmail is supplyed and nothing else?

**Comment by jcormier** [comment]
This is a bit confusing as the current email settings don't have to use a gmail email server they just default to it.  Both SMTP_HOST and IMAP_HOST allow you to specify a different email server.  So I don't think we want to always rely on sendmail if they want to use something other than gmail.

Note that I have run into a email service (fastmail) which the rails email client wouldn't work due to some bug. In that case we did use a sendmail setup using the msmtp package.  I think this was the bug https://rails.lighthouseapp.com/projects/8994/tickets/1731-make-enable_starttls_auto-opt-in-in-actionmailer#ticket-1731-18. Though I didn't use the docker image for this redmine install.

Still not sure how common it is that the rails email client won't work with an email server and its always possible it was fixed in the newer version of ruby.

**Comment by frank-dspeed** [comment]
@jcormier i mean shouldn't that be able to send emails in general without gmail directly without extra email server setup?

**Comment by jcormier** [comment]
Ahh sounds like your asking about sending emails without a SMTP relay.  Described here: https://afterlogic.com/mailbee-net/docs/direct_send.html

I hadn't really considered this.  The link above mentions this is not advised as many email servers will block these direct sent emails as they are often spam.

> Even more important vote for SMTP relay is the fact that most e-mail services nowadays do not accept e-mail from hosts which are not full-fledged SMTP servers. This is because "direct send" mode is widely used by spammers' bot networks. A typical e-mail service, after it receives the incoming request to deliver an e-mail to it, makes reverse connection to the client's host, checks if that host is an SMTP server itself, if it has properly configured DNS MX, PTR, and SPF records, and so on.

From OP's limited example, he should be able to create a redmine account with his companies email provider and use it to send emails from without relying on direct-sent emails.

**Comment by frank-dspeed** [comment]
@jcormier ok we don't integrate sendmail and point to the documentation aka readme for that if there is something in about configuring email

**Comment by jcormier** [comment]
Closed due to old age
