### ISSUE TITLE
The error of repository "404 The entry or revision was not found in the repository."

### ISSUE THREAD

**Issue by luckygg** [sameersbn/docker-redmine#354]
Hi all.

I have a question about repository with Git.

My environments is as below :
(I'm using the Redmine on Synology NAS, Git server on Synology NAS.)
Environment:
  Redmine version                3.3.6.stable
  Ruby version                   2.3.6-p384 (2017-12-14) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Darcs                          2.8.4
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.16.1
  Filesystem                     
  GitRemote                      2.16.1

I referred the links :
http://www.codenutz.com/bolts/getting-started-git-synology-nas/
http://yourpresence.tistory.com/38 (this link is Korean.. but I think it's okay because the commands)

So, my problem is "404 The entry or revision was not found in the repository."

I can not find a solution for 2 weeks..

Please somebody help me. 

Thank you.

**Comment by jcormier** [comment]
This sounds like a redmine setup issue.  However I'm unclear where you get this error and how the repository was setup.

**Comment by jcormier** [comment]
Sounds like you setup the git repository so that it can be pulled and pushed to.  However, redmine can't directly connect to this.  It needs a mirror setup that it can access directly, I don't know why redmine makes this so difficult.  

http://www.redmine.org/projects/redmine/wiki/HowTo_Easily_integrate_a_(SSH_secured)_GIT_repository_into_redmine

I don't know if its possible to point redmine directly to the bare repo (all the guides talk of using mirror repos) you created at /var/services/homes/gituser/test.git, but you would have to mount it in the docker as a volume if you wanted to try.

**Comment by luckygg** [comment]
Hi jcormier.

Thank you for your advise!!

I succeeded in connecting the remote repository.

Thank you, have a great day!
