### ISSUE TITLE
Implement reminder mails

### ISSUE THREAD

**Issue by prodigy7** [sameersbn/docker-redmine#401]
Related to https://www.redmine.org/projects/redmine/wiki/RedmineReminderEmails I wish, reminder functionality would be implemented. Hopefully it isn't a big deal :)

**Comment by jcormier** [comment]
Sorry for the late reply.  This feature seems like a mess.  A lot of these settings should have been configurable in the website instead of requiring the cronjob to be changed everytime a new user is added....

It doesn't seem like it would be too hard to add some ENV variables to enable and configure a cronjob.  Similar to how the email ones work.  However, I don't have the time to implement and test it.  

Feel free to submit a pull request.  Or you could create a plugins/post-install.sh file to create the cron job. See the https://github.com/sameersbn/docker-redmine#installing-plugins section for example.

**Comment by jcormier** [comment]
Yup though your solution is decent.  I'd normally create the cronjob inside the container using the plugins/post-install.sh script but I've definitely made scripts similar to yours to call from the host.

Closing this issue.

**Comment by marcosguedes** [comment]
Thanks for the tip! I'll definitely do that!

**Comment by jcormier** [comment]
Yeah something similar is mentioned in the install plugins section.
https://github.com/sameersbn/docker-redmine?tab=readme-ov-file#installing-plugins
