### ISSUE TITLE
SMTP SSL not working without SSL=true

### ISSUE THREAD

**Issue by radoslavius** [sameersbn/docker-redmine#513]
Hi,

on the basis of issue #117 I am inserting a new issue

With this setting, email sending will end on timeout

```
- SMTP_ENABLED=true
- SMTP_METHOD=smtp
- SMTP_DOMAIN=xxx
- SMTP_HOST=smtp.forpsi.com
- SMTP_PORT=465
- SMTP_USER=xxx
- SMTP_PASS=xxx
- SMTP_AUTHENTICATION=:login
```
Settings is from documentation of my email server provider:
https://support.forpsi.com/kb/a3969/email-clients-settings.aspx?KBSearchID=565945

Currently I solved it by creating a custom image, which adds a single command to your image:

```
RUN sed -i "s/  {{SMTP_METHOD}}_settings:/  {{SMTP_METHOD}}_settings:\n    ssl: true/g" /etc/docker-redmine/runtime/config/redmine/configuration.yml
```

Thanks

**Comment by radoslavius** [comment]
I apologize for my "super fast" response. I'm not sure if I tested it correctly.
For the build, I used this command:

```
docker build -t redmine_add_smtp_ssl https://github.com/sameersbn/docker-redmine.git#add_smtp_ssl
```

Then I sent a test email, and it looks good.

Thanks.

**Comment by jcormier** [comment]
merged into master branch and released in tag 5.1.1-3

**Comment by rro-mcse** [comment]
Hello,
I did recently change my email provider, updated to 4.2 stable (4.2.11-1) and stumbled upon the same problem.
Would you be able to apply the same patch to the other branch?

I'm currently using another config with STARTTLS at the moment to get around the problem but my mail provider discourages the use of STARTTLS.
Thanks

**Comment by jcormier** [comment]
> I did recently change my email provider, updated to 4.2 stable (4.2.11-1) and stumbled upon the same problem.

I pushed some commits to the 4.2-stable branch. Can you test it and I'll release a tagged version if it works

**Comment by rro-mcse** [comment]
I had some trouble building the image from source as I'm usually pulling it but it's running fine with SSL on SMTP for mails notifications now with my locally built image

To build the image successfully I had to change all occurences of `keyserver.ubuntu.com` to `hkp://keyserver.ubuntu.com:80` because I was getting these errors: 
`gpg: keyserver receive failed: Connection timed out` or `gpg: keyserver receive failed: Cannot assign requested address`
when the Dockerfile was running:
`Executing: /tmp/apt-key-gpghome.V6EzI7wnpu/gpg.1.sh --keyserver keyserver.ubuntu.com --recv E1DD270288B4E6030699E45FA1715D88E1DF1F24`

**Comment by jcormier** [comment]
Okay 4.2.11-2 released
