### ISSUE TITLE
Multiple problems on rebuilding the redmine image

### ISSUE THREAD

**Issue by R4P70R** [sameersbn/docker-redmine#532]
I have a redmine server that was running on 4.2.2 and was using a backup script running every Sunday which docker-compose down, backup everything and docker-compose up -d and which have been working great for the last year.
But last Sunday, the redmine server failed to turn back on.

Quickly I found out that the error was coming from a signature missing
<pre>
> Err:1 http://repo.mysql.com/apt/ubuntu bionic InRelease
> redmine_1     |   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7B3B788A8D3785C
> ...
> redmine_1     | W: GPG error: http://repo.mysql.com/apt/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7B3B788A8D3785C
> redmine_1     | E: The repository 'http://repo.mysql.com/apt/ubuntu bionic InRelease' is not signed.
> redmine_1     | N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> redmine_1     | N: See apt-secure(8) manpage for repository creation and user configuration details.
> docker-redmine_redmine_1 exited with code 100
</pre>
Not a big deal I thought, I can update the signature 467B942D3A79BD29 to B7B3B788A8D3785C in the Dockerfile and rebuild.
Out of precaution, I've tried to copy the config and do it on another machine, the fix was working but I found out that another error would have stopped me from rebuilding this image.
<pre>
> ERROR:  Error installing bundler:
> The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.4.22. Try installing it with `gem install bundler -v 2.4.22`
> bundler requires Ruby version >= 3.0.0. The current ruby version is 2.6.6.146.
> ------
> Dockerfile:38
</pre>
I've tried to isolate the problem by tweaking the Dockerfile and add the different commands like proposed:
`gem install bundler -v 2.4.22`
`gem update --system 3.2.3`
I can build the image but it doesn't really work in the end and fail to proceed while starting up
<pre>
> redmine_1     | Configuring nginx::redmine...
> redmine_1     | Migrating database. Please be patient, this could take a while...
> redmine_1     | Your RubyGems version (3.0.3) has a bug that prevents `required_ruby_version` from working for Bundler. Any scripts that use `gem install bundler` will break as soon as Bundler drops support for your Ruby version. Please upgrade RubyGems to avoid future breakage and silence this warning by running `gem update --system 3.2.3`
> redmine_1     | rake aborted!
> redmine_1     | NameError: uninitialized constant Nokogiri::HTML4
> ...
> redmine_1     | /var/lib/gems/2.6.0/gems/bundler-2.4.22/lib/bundler.rb:187:in `require'
> redmine_1     | /home/redmine/redmine/config/application.rb:18:in `<top (required)>'
> redmine_1     | /home/redmine/redmine/Rakefile:5:in `require'
> redmine_1     | /home/redmine/redmine/Rakefile:5:in `<top (required)>'
> redmine_1     | /home/redmine/data/tmp/bundle/ruby/2.6.0/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
> redmine_1     | (See full trace by running task with --trace)
> docker-redmine_redmine_1 exited with code 1
</pre>

Well maybe it's time to update to the latest version to have a newer Ruby version then. 
To my surprise, using the last tagged "release: 5.1.1" gave me another very similar error
<pre>
> ERROR:  Error installing bundler:
> The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.4.22. Try installing it with `gem install bundler -v 2.4.22`
> bundler requires Ruby version >= 3.0.0. The current ruby version is 2.7.5.203.
> ------
> Dockerfile:38
</pre>
At this point I stopped trying because I'm no expert in troubleshooting ruby and I hope someone has a tip, can help me on how to proceed or tell me what I'm doing wrong. I don't think there is any way to bypass rebuilding the image but maybe I'm wrong.
I was happily using it reliably and I didn't touch the config of this server since a very long time ago.
Thanks

**Comment by jcormier** [comment]
Can you share what your docker-compose file looks like?  Do you have your own custom Dockerfile? Are you using any redmine plugins?  Please attach the whole startup log.

Note that a normal up of the container should not kick off a build of the image, but instead pull it from the docker hub. You can force it to pull the image using 'docker pull sameersbn/redmine:4.2.2'. Though usually docker compose handles that automatically.  You can remove the build; step from the compose file to force it... 

I can confirm that the debian version used by the 4.2 branch and even master no longer builds due to the signature mismatch.  Mysql must have changed this very recently...

> Well maybe it's time to update to the latest version to have a newer Ruby version then.
> To my surprise, using the last tagged "release: 5.1.1" gave me another very similar error

Are you using any plugins?  If not then upgrading redmine versions usually goes smoothly.  If you are then the plugins likely need to be upgraded first (if they even have upgrades) to support a newer redmine version.  Upgrading plugins is usually the hardest part of moving to newer redmine versions for me atleast...


> > ERROR: Error installing bundler:

I recommend at this point to save a copy of the current database and data directory (rename the redmine/mysql directories?), just in case you need it. Manually pull the 4.2.2 image. Restore from your last backup so you are back to 4.2.2.  Once things are back up and running, you can test your redmine upgrades by making a 2nd copy of the redmine instance, restoring from backup or just copying the directories, and upgrading your copy so you can make sure all goes well before trying it on the main one.

**Comment by jcormier** [comment]
Note that along with the mysql signing key change, bundler also released an update last week which removed support for ruby 2.7.  So I pinned the bundler version to the last working version.

Fixes for the build issues have been pushed to the 4.2-stable, 5.0-stable, and master branch. As well as updated images 4.2.11-1, 5.0.7-2, and 5.1.1-1

**Comment by R4P70R** [comment]
Thanks for the responsiveness and all your tips @jcormier 
I was able to restore my server and everything to work again.

First by commenting out the build step in the docker-compose.yml and then found out that the plugins/pre-install.sh was failing now due to the same public key missing but fixed it by adding the following lines at the start of the script
<pre>
apt-get update -y || true
apt-get install -y wget gnupg2
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv B7B3B788A8D3785C
echo "deb http://repo.mysql.com/apt/ubuntu/ bionic mysql-5.7" >> /etc/apt/sources.list
</pre>
And then everything was running smoothly again

So yes I'm using multiple plugins and I don't want to spend too much time maintaining or breaking this server but I'm planning on trying to migrate this one to the latest 4.2-stable when possible. The backup of the whole server is automated every week so I can try this on another machine easily

I'm happy of my very small contribution at spotting the Mysql issue 😄
