### ISSUE TITLE
"Stay logged in" feature is not available

### ISSUE THREAD

**Issue by tf-r-hatanaka** [sameersbn/docker-redmine#569]
A ticket with the same title has been posted officially on REDMINE.

https://www.redmine.org/issues/41823

In this discussion, it is said to be a problem with `sameersbn/redmine`. 
It is also said that the cause is that unicorn 6.1.0 does not support Rack3.

Please check and fix the problem.

**Comment by jcormier** [comment]
Note there doesn't appear to be an updated version of unicorn despite this allegedly being fixed in June.  The 6.1.0 version was released in 2021 so it seems like its not being actively supported.

Considering that I think it would be a good idea to migrate to either https://puma.io/ or https://www.phusionpassenger.com.

Currently leaning towards puma since it more closely matches how unicorn is setup and thus may break fewer users expectations.

**Comment by jcormier** [comment]
A short term fix looks like it could be to avoid upgrading to rack 3

> After more digging in the mailing lists, I found that the incompatibility is caused by a change in Rack 3, so one possible solution without having to patch unicorn is to specify gem 'rack', '< 3' as a dependency. This seems to work for me so far; I've successfully deployed to staging.

**Comment by jcormier** [comment]
> A short term fix looks like it could be to avoid upgrading to rack 3

redmine 6 depends on rack >= 3.1.3 so this doesn't seem like a viable solution

gem 'rack', '>= 3.1.3'

**Comment by jcormier** [comment]
@tf-r-hatanaka I pushed an update to the master branch.  I tried your instructions and changing to the puma server is working for me.  Can you test and verify it fixes things for you?

**Comment by tf-r-hatanaka** [comment]
@jcormier 
I have confirmed that the issue has been fixed.
Thank you for your quick response.

**Comment by jcormier** [comment]
Thanks. Released tagged version 6.0.1-1
