### ISSUE TITLE
Connecting mysql on host

### ISSUE THREAD

**Issue by ploef** [sameersbn/docker-redmine#71]
Hi,
First of all, thanks for the great work on this image! Unfortunately I'm having a problem connecting to my mysql server on the host. Using 127.0.0.1 does not work, so I think I have to use a socket connection.
The problem is I don't know how to configure this using the environment variables.
Could you point me in the right direction?

Best regards,
Peter

**Comment by sameersbn** [comment]
@ploef using `127.0.0.1` will not work, because it would address the container itself. If you are trying to connect to a mysql server that is running on the same host as the container you should rather use `172.17.42.1` or whatever the output of `ifconfig docker0` is. Also make sure the mysql user is allowed remote access originating from the `172.17.%.%` address space.

Use of the mysql socket is technically possible, but not yet supported by the image so it will not work at the moment.

**Comment by sameersbn** [comment]
@ploef did you get the issue resolved?
