### ISSUE TITLE
no volumes in fig.yml

### ISSUE THREAD

**Issue by so0k** [sameersbn/docker-redmine#73]
Would it be better to put arbitrary volumes under fig.yml?

**Comment by sameersbn** [comment]
@so0k whhat do you mean by arbitrary volumes?

**Comment by so0k** [comment]
sorry for late reply, maybe arbitrary is the wrong word (non-native speaker here).

I meant - add a 'default' volume mapping for the data store in the fig file (and rename fig to docker-compose.yml)

**Comment by sameersbn** [comment]
@so0k docker compose feature is not released yet right? I don't see `docker up` option in `1.4.1`. Until the compose feature is available it does not make sense to rename the fig.yml file. Once the feature is out in the open the required changes can be done with updates to the readme as well.

Regarding the volume statement in `fig.yml`, since it is a sample configuration it does not make sense to add a volume instruction in there. User are expected to build upon this sample as per their requirements.

**Comment by so0k** [comment]
you are right
