### ISSUE TITLE
Redmine 3.0.1 Container will not start after power failure

### ISSUE THREAD

**Issue by bignay2000** [sameersbn/docker-redmine#91]
Created by :  docker run --name=xxxxredmine -h xxxxredmine -d -p 10.10.10.160:80:80 -p 10.10.10.160:443:443 -p 10.10.10.160:22:22 -v /var/run/docker.sock:/run/docker.sock -v $(which docker):/bin/docker sameersbn/redmine:3.0.1

Upgraded from the previous 2.6 version.  Everything upgraded great and server was running well.

Then I accidentally powered off my Ubuntu Docker host (id10T).  Now the container will not start and exits within 1 second.  Starting this container does start the database.

root@xxxx:~# docker start -i 7e07bd263da2
Database connection details not specified.
Will try to spin up a new postgresql image with the name postgresql-redmine.
Please manually configure the database connection in production.
Using existing postgresql container...
Waiting for database server to accept connections
Migrating database. Please be patient, this could take a while...
/var/lib/gems/2.1.0/gems/bundler-1.9.1/lib/bundler/resolver.rb:333:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'rails (= 4.2.0) ruby' in the gems available on this machine. (Bundler::GemNotFound)
	from /var/lib/gems/2.1.0/gems/bundler-1.9.1/lib/bundler/resolver.rb:307:in `each'
	from /var/lib/gems/2.1.0/gems/bundler-1.9.1/lib/bundler/resolver.rb:307:in `verify_gemfile_dependencies_are_found!'
	from /var/lib/gems/2.1.0/gems/bundler-1.9.1/lib/bundler/resolver.rb:199:in `start'
	from /var/lib/gems/2.1.0/gems/bundler-1.9.1/lib/bundler/resolver.rb:182:in `resolve'
	from /var/lib/gems/2.1.0/gems/bundler-1.9.1/lib/bundler/definition.rb:193:in `resolve'
	from /var/lib/gems/2.1.0/gems/bundler-1.9.1/lib/bundler/definition.rb:132:in `specs'
	from /var/lib/gems/2.1.0/gems/bundler-1.9.1/lib/bundler/definition.rb:177:in `specs_for'
	from /var/lib/gems/2.1.0/gems/bundler-1.9.1/lib/bundler/definition.rb:166:in `requested_specs'
	from /var/lib/gems/2.1.0/gems/bundler-1.9.1/lib/bundler/environment.rb:18:in `requested_specs'
	from /var/lib/gems/2.1.0/gems/bundler-1.9.1/lib/bundler/runtime.rb:13:in `setup'
	from /var/lib/gems/2.1.0/gems/bundler-1.9.1/lib/bundler.rb:122:in `setup'
	from /var/lib/gems/2.1.0/gems/bundler-1.9.1/lib/bundler/setup.rb:18:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'

**Comment by bignay2000** [comment]
Able to copy my data folder out of the stopped container
docker cp 7e07bd263da2:/home/redmine/data /root/redminedata

Going to reinstall.

**Comment by sameersbn** [comment]
@bignay2000 You have used the quickstart guide to start the container, which goes and start a postgresql container for you. Note this is only for testing purposes. You should manually (or using fig/docker-compose) configure the image and its requirements as specified in the README. This includes mounting data volumes for the redmine as well as the mysql or postgresql container.

Mounting volumes for your container ensures that there is no data loss when the container(s) is stopped/deleted/started because all the data is left intact for you to recreate the container.

The quickstart guide is only present to allow new users to quickly take a look at what redmine offers. It is not intended or tested to be used on production. Production installs require that you read the README beyond the quick start guide.

As far as the error above goes, I myself have never tried using the quickstart guide to start the container and then stop them and start again. Whatever the cause of the error, it would be difficult to give you instructions on how to recover from it.

**Comment by sameersbn** [comment]
@bignay2000 i just tested starting the redmine container as per the quick start guide. Then stopped the redmine and redmine-postgresql containers and started the redmine container again using `docker start redmine` and everything started up fine and with no errors.

Maybe you had some data loss/corruption when the host pc was powered off.

**Comment by bignay2000** [comment]
This issue was caused by me.  When I upgraded from Redmine 2.6, I moved the entire /home/redmine/data directory to the new Redmine 3.0.1 container's /home/redmine/data.  This ran great until Redmine was stopped and then tried to start with a data/tmp folder from the older (2.6) version.

Reinstalled 3.0.1 and only copied the /home/redmine/data/files directory to the new container (dotfiles was empty not sure what this directory is for and omitted it too).  Container can now be stopped and started.  Also confirmed attachments are working.

Awesome.   A BIG THANK YOU to sameersbn for responding quickly to this issue.
